### ISSUE TITLE
undefined method `blog' #<Middleman::CoreExtensions::Data::DataStore>

### ISSUE THREAD

**Issue by e2** [middleman/middleman-blog#16]
I was wondering if middleman-blog is supposed to work with middleman 3.0.

After a quick look, it doesn't seem to register properly. I wanted to ask before diving into the code.

(I'm using repositories directly, not gems).

Thanks!
